### ISSUE TITLE
max token pop alert

### ISSUE THREAD

**Issue by bb33bb** [jackschedel/KoalaClient#105]
![image](https://github.com/jackschedel/KoalaClient/assets/5463104/4af6d445-992a-4e6a-a3e9-bd3fc87b1d2e)

the other software named "better chatgpt" is ok and will not pop error

I build the latest version of KoalaClient , which pop this alert.

**Comment by Yardanico** [comment]
@bb33bb "Max tokens" is for specifying how much tokens a model can generate at max, the max value for gpt-4-1106-preview is 4096 tokens. You should change it to 4096, and you already have Max Context set up properly.

**Comment by bb33bb** [comment]
> @bb33bb "Max tokens" is for specifying how much tokens a model can generate at max, the max value for gpt-4-1106-preview is 4096 tokens. You should change it to 4096, and you already have Max Context set up properly.

thanks for your tips.
I am going to try it.

**Comment by bb33bb** [comment]
> @bb33bb "Max tokens" is for specifying how much tokens a model can generate at max, the max value for gpt-4-1106-preview is 4096 tokens. You should change it to 4096, and you already have Max Context set up properly.

totaly right.
Sorry to bother u
