### ISSUE TITLE
support gpt4-tubor-preview?

### ISSUE THREAD

**Issue by bb33bb** [jackschedel/KoalaClient#106]
is it ok to support this ?
![image](https://github.com/jackschedel/KoalaClient/assets/5463104/f854d923-7a3a-451a-8a8b-dd4559f84520)

**Comment by jackschedel** [comment]
2.0.8d PR will change gpt4-1106-preview to gpt4-turbo-preview

2.0.9 (in the works) will ensure that any future models are easily supported, as users will be able to manually specify any model.
