### ISSUE TITLE
after upgrade to latest, have to delete all config and restart the software. The old config files have to be exported and imported

### ISSUE THREAD

**Issue by bb33bb** [jackschedel/KoalaClient#108]
after upgrade to latest, have to delete all config and restart the software. The old config files have to be exported and imported
imported error

**Comment by jackschedel** [comment]
Hi, why did you close this as completed? Is this issue resolved?

**Comment by jackschedel** [comment]
this should be fixed in 2.0.8e, there was a migration edge case.

**Comment by bb33bb** [comment]
> this should be fixed in 2.0.8e, there was a migration edge case.

fixed bro
because I really feeled that I was so boring to trobule u so much.
really sorry to give u so much work.
All were patched.
