### ISSUE TITLE
new api gpt-4-0125-preview

### ISSUE THREAD

**Issue by bb33bb** [jackschedel/KoalaClient#110]
gpt-4-0125-preview is a new api added in Openai.
we can add it.
Thanks!!

**Comment by jackschedel** [comment]
`gpt-4-turbo-preview` currently points to this model.
see https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo

**Comment by bb33bb** [comment]
> `gpt-4-turbo-preview` currently points to this model. see https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo

u win again
Thanks !!
