### ISSUE TITLE
possible to add gpt-4-turbo-2024-04-09 ?

### ISSUE THREAD

**Issue by bb33bb** [jackschedel/KoalaClient#123]
possible to add gpt-4-turbo-2024-04-09 ?

**Comment by jackschedel** [comment]
Hi, `gpt-4-turbo` automatically points to the latest gpt-4 model in their api:

<img width="702" alt="image" src="https://github.com/jackschedel/KoalaClient/assets/26682594/9a591728-2dda-4b77-8328-0f7f9abca0ba">
(https://platform.openai.com/docs/models/continuous-model-upgrades)

**Comment by bb33bb** [comment]
thanks!!
